import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Book, BookService } from '../book.service';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-book-detail',
  imports: [FormsModule, CommonModule,MatCardModule,MatButtonModule],
  templateUrl: './book-detail.component.html',
  styleUrl: './book-detail.component.css'
})
export class BookDetailComponent {

  Description:any;
  title:any;

  constructor(private route:Router){
    //alert(sessionStorage.getItem('title'))
    if(sessionStorage.getItem('title')=='Harry Potter'){
      this.Description = "Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. The novels chronicle the lives of a young wizard, Harry Potter, and his friends, Ron Weasley and Hermione Granger, all of whom are students at Hogwarts School of Witchcraft and Wizardry. The main story arc concerns Harry conflict with Lord Voldemort, a dark wizard who intends to become immortal, overthrow the wizard governing body known as the Ministry of Magic, and subjugate all wizards and Muggles.The series was originally published in English by Bloomsbury in the United Kingdom and Scholastic Press in the United States. A series of many genres, including fantasy, drama, coming-of-age fiction, and the British school story (which includes elements of mystery, thriller, adventure, horror, and romance), the world of Harry Potter explores numerous themes and includes many cultural meanings and references. Major themes in the series include prejudice, corruption, madness, love, and death.Since the release of the first novel, Harry Potter and the Philosophers Stone, on 26 June 1997, the books have found immense popularity and commercial success worldwide. They have attracted a wide adult audience as well as younger readers and are widely considered cornerstones of modern literature,though the books have received mixed reviews from critics and literary scholars.As of February 2023, the books have sold more than 600 million copies worldwide, making them the best-selling book series in history, available in dozens of languages. The last four books all set records as the fastest-selling books in history, with the final instalment selling roughly 2.7 million copies in the United Kingdom and 8.3 million copies in the United States within twenty-four hours of its release. It holds the Guinness World Record for Best-selling book series for children.Warner Bros. Pictures adapted the original seven books into an eight-part namesake film series. In 2016, the total value of the Harry Potter franchise was estimated at $25 billion, making it one of the highest-grossing media franchises of all time. Harry Potter and the Cursed Child is a play based on a story co-written by Rowling. A television series based on the books is in production at HBO.The success of the books and films has allowed the Harry Potter franchise to expand with numerous derivative works, a travelling exhibition that premiered in Chicago in 2009, a studio tour in London that opened in 2012, a digital platform on which J. K. Rowling updates the series with new information and insight, and a trilogy of spin-off films premiering in November 2016 with Fantastic Beasts and Where to Find Them, among many other developments. Themed attractions, collectively known as The Wizarding World of Harry Potter, have been built at several Universal Destinations & Experiences amusement parks around the world."
      this.title = sessionStorage.getItem('title')
    }

    if(sessionStorage.getItem('title')=='Mission Impossible'){
      this.Description = 'Mission: Impossible is a series of American action spy films, based on the 1966 TV series created by Bruce Geller. The series is mainly produced by Tom Cruise, who plays Ethan Hunt, an agent of the Impossible Mission Force (IMF). The films have been directed, written, and scored by various filmmakers and crew, while incorporating musical themes from the original series by Lalo Schifrin.Starting in 1996, it follows the missions of the IMFs main field team, under Hunts leadership, to stop an enemy force and prevent an impending global disaster. The series focuses on Hunts character, and like the television series structure, is complemented by an ensemble cast, such as Luther Stickell (played by Ving Rhames) and Benji Dunn (played by Simon Pegg), who have recurring roles.The series has experienced a generally positive reception from critics. It is the 17th-highest-grossing film series of all time, earning over $4.09 billion worldwide,[1] and is often cited as one of the best action franchises to date. The sixth film, subtitled Fallout, was released on July 27, 2018 and is currently the series highest-grossing entry. The seventh and most recent film, Dead Reckoning Part One,[a] was released in July 2023, and an eighth film, The Final Reckoning, is scheduled for release in May 2025. The films are co-produced and released by Paramount Pictures.Numerous efforts by Paramount Pictures to create a film adaptation of the television series stalled until Cruise founded Cruise/Wagner Productions in 1992 and decided on Mission: Impossible as its inaugural project. Development initially began with filmmaker Sydney Pollack but most of the final screenplay was completed after De Palma, Steven Zaillian, David Koepp and Robert Towne were hired; De Palma also designed most of the action sequences, while Cruise did most of his own stunts. Principal photography began in March 1995 and lasted until that August, with filming locations including London, Pinewood Studios in England, and Prague (a rarity in Hollywood at the time).Mission: Impossible was theatrically released in the United States by Paramount on May 22, 1996. The film received generally positive reviews from critics, with praise for the action sequences, De Palmas direction and Cruises performance, but criticism for a convoluted plot. The film grossed $457.7 million worldwide, making it the third-highest-grossing film of 1996, while the dance rendition of the original theme song by Larry Mullen Jr. and Adam Clayton became a top-ten hit internationally and was nominated for the Grammy Award for Best Pop Instrumental Performance. The films success led to a long-running film franchise, beginning with Mission: Impossible 2, released four years later in 2000.'
      this.title = sessionStorage.getItem('title')
    }

    if(sessionStorage.getItem('title')=='Kanchana'){
      this.Description = 'Raghava, an unemployed youth, has developed irrational phasmophobia and refuses to step out of his house after sunset, chooses to sleep in his mothers room, and forces her to accompany him to the restroom at night. His antics disrupt the peace of his family, which includes his widowed mother, Vatsala, his elder brother Prasad, the latters wife Kamakshi, and their children. Raghava and his companions, who usually play cricket on the ground, are compelled to search for another as construction activity is to take place in it, and unwittingly choose an abandoned land, which is believed to be haunted by supernatural forces.While they try setting up the cricket pitch, a peculiar weather change causes them to abandon the land and return home. Still, Raghava does not notice that his cricket stumps are stained with blood after piercing corpses buried under the land. Raghava woos Kamakshis younger sister Priya, who has come to stay with them, while Vatsala and Kamakshi become panic-stricken by perpetual supernatural occurrences at their residence. Hiding it from their family, Vatsala and Kamakshi consult a priest, who suggests three rituals to test the presence of a spirit in their home. Raghava, Priya, and the kids get sent to Kamakshis maternal home to check on Kamakshis ill father, a lie told to prevent Raghava from obstructing the rituals. Vatsala and Kamakshis suspicions turn out to be true after they perform the rituals and to chase the ghost away, they hire two priests, who ask them to stay outside the house while they try to capture the ghost. However, they are con men chased away from the house but mislead Vatsala and Kamakshi into believing that they have seized the ghost, and they get paid. Raghava, Priya, and the kids return home the next day. On the same night, the spirit possesses Raghava.From the succeeding day, Raghava begins to act effeminate and detaches himself from Priya. While in a shopping complex with his mother and sister-in-law, Raghava continues to act unmanly and wears a saree and womens jewellery, embarrassing Vatsala, who slaps him. Raghava strangles a woman, Madhavi, to death and later disposes of her corpse, unbeknownst to anyone. Kamakshi, that night, witnesses Raghava wearing her bangles and eventually exposes his womanish acts to Prasad, and the family confronts him. Then, the family discovers that Raghava is possessed by three spirits: a woman, an Urdu-speaking Muslim, and an autistic man. Frightened, the family approaches a Muslim exorcist, who drives the spirit away from Raghavas body and forces the womans spirit to reveal who she is. The woman discloses herself as a transgender woman, Kanchana, who reveals her past.'
      this.title = sessionStorage.getItem('title')
    }
  }

  exit(){
    this.route.navigate(['/book-list']);
  }
}

